#!/bin/bash

# ゴミ箱の場所
trash="$HOME/trash"

# ゴミ箱ディレクトリを作成
if [ ! -d ${trash} ]; then
    mkdir ${trash}
fi

# オプションを無視
while [[ $1 = -* ]]
do
    shift
done

# 引数がない場合は使い方を表示
if [ $# -eq 0 ]; then
    echo "usage: trash <file|dir> ..."
    exit 1
fi

# 移動処理
for file in $@
do
    # ファイルの存在チェック
    if [ ! -e ${file} ]; then
        echo -e "[ \e[31mNG\e[m ] '${file}': No such file or directory"
        continue
    fi

    # ファイル名を生成
    name=$(echo ${file} | sed -e 's|/$||; s|.*/||')
    path_tmp=${trash}/${name}
    path=${path_tmp}
    i=1
    while true
    do
        if [ -e ${path} ]; then
            path=${path_tmp}_${i}
            i=$((i + 1))
        else
            break
        fi
    done

    # 移動
    mv ${file} ${path} &> /dev/null
    if [ $? -eq 0 ]; then
        echo -e "[ \e[32mOK\e[m ] ${file} -> ${path}"
    else
        echo -e "[ \e[31mNG\e[m ] ${file} -> ${path}"
        exit 1
    fi
done
exit 0